// Code generated by togo. GraphQL resolvers for Note via the ORM — safe to edit.
package resolvers

import (
	"context"

	db "github.com/fadymondy/mark-it-down/apps/web/internal/db/gen"
	graphgen "github.com/fadymondy/mark-it-down/apps/web/internal/graph/gen"
	"github.com/fadymondy/mark-it-down/apps/web/internal/models"
)

func (r *queryResolver) Note(ctx context.Context, id string) (*db.Note, error) {
	return models.Notes(r.App).Find(ctx, id)
}

func (r *queryResolver) Notes(ctx context.Context) ([]*db.Note, error) {
	rows, err := models.Notes(r.App).Order("created_at DESC").Limit(100).Get(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*db.Note, len(rows))
	for i := range rows {
		out[i] = &rows[i]
	}
	return out, nil
}

func (r *mutationResolver) CreateNote(ctx context.Context, input graphgen.CreateNoteInput) (*db.Note, error) {
	row, err := models.Notes(r.App).Create(ctx, map[string]any{
		"title":      input.Title,
		"body":       input.Body,
		"category":   input.Category,
		"tags":       input.Tags,
		"user_id":    input.UserID,
		"share_slug": input.ShareSlug,
		"is_public":  input.IsPublic,
	})
	if err != nil {
		return nil, err
	}
	r.App.Emit(ctx, "note.created", row)
	return row, nil
}

func (r *mutationResolver) DeleteNote(ctx context.Context, id string) (bool, error) {
	if err := models.Notes(r.App).Where("id", "=", id).Delete(ctx); err != nil {
		return false, err
	}
	r.App.Emit(ctx, "note.deleted", id)
	return true, nil
}
