// Code generated by togo. Eloquent-style query entry for Note.
// Driver-agnostic (dialect from DB_DRIVER). Examples:
//
//	models.Notes(a).Find(ctx, id)
//	models.Notes(a).Where("title", "ILIKE", "%x%").Order("created_at DESC").Get(ctx)
package models

import (
	"github.com/togo-framework/orm"

	"github.com/fadymondy/mark-it-down/apps/web/internal/app"
	db "github.com/fadymondy/mark-it-down/apps/web/internal/db/gen"
)

// Notes starts a query against the notes table.
func Notes(a *app.App) *orm.Query[db.Note] {
	return orm.For[db.Note](a.SQLDB, a.Dialect, "notes")
}
