// Code generated by togo. Next.js page for Notes.
"use client";

import { useNotes } from "@/lib/hooks/useNotes";

export default function NotesPage() {
  const { data, isLoading } = useNotes();
  if (isLoading) return <p>Loading…</p>;
  return (
    <main className="p-6">
      <h1 className="text-2xl font-bold">Notes</h1>
      <ul>
        {data?.map((item) => (
          <li key={item.id}>{item.id}</li>
        ))}
      </ul>
    </main>
  );
}
