// Code generated by togo. API type for Note.
export interface Note {
  id: string;
  title: string;
  body: string;
  category?: string;
  tags?: string;
  userID: string;
  shareSlug?: string;
  isPublic: boolean;
  created_at: string;
  updated_at: string;
}
