-- Code generated by togo. SQLite schema fragment for sqlc and migrate.
CREATE TABLE IF NOT EXISTS notes (
    id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    title text NOT NULL,
    body text NOT NULL,
    category text,
    tags text,
    user_id text NOT NULL,
    share_slug text,
    is_public boolean NOT NULL,
    created_at datetime NOT NULL DEFAULT (datetime('now')),
    updated_at datetime NOT NULL DEFAULT (datetime('now'))
);
