// Code generated by togo. Data hook for Notes.
import useSWR from "swr";

import { apiFetch } from "@/lib/api/client";
import type { Note } from "@/lib/api/note";

export function useNotes() {
  return useSWR<Note[]>("/notes", apiFetch);
}
