// Code generated by togo. API Resource transformer for Note — customize
// the response shape here (Laravel-style API Resources). REST handlers return this.
package resources

import (
	"time"

	db "github.com/fadymondy/mark-it-down/apps/web/internal/db/gen"
)

// NoteResponse is the JSON shape returned by the Note API.
type NoteResponse struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	Category  *string   `json:"category"`
	Tags      *string   `json:"tags"`
	UserID    string    `json:"user_id"`
	ShareSlug *string   `json:"share_slug"`
	IsPublic  bool      `json:"is_public"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// TransformNote maps a db row to the API response. Edit freely.
func TransformNote(m db.Note) NoteResponse {
	return NoteResponse{
		ID:        m.ID,
		Title:     m.Title,
		Body:      m.Body,
		Category:  m.Category,
		Tags:      m.Tags,
		UserID:    m.UserID,
		ShareSlug: m.ShareSlug,
		IsPublic:  m.IsPublic,
		CreatedAt: m.CreatedAt,
		UpdatedAt: m.UpdatedAt,
	}
}

// TransformNotes maps a slice of db rows to API responses.
func TransformNotes(rows []db.Note) []NoteResponse {
	out := make([]NoteResponse, len(rows))
	for i, m := range rows {
		out[i] = TransformNote(m)
	}
	return out
}
