/**
 * Minimal EPUB 3.0 builder. Produces an in-memory .epub buffer from a
 * list of markdown chapters + optional cover image.
 *
 * Structure produced:
 *   mimetype                                 (stored, must be first)
 *   META-INF/container.xml
 *   OEBPS/content.opf
 *   OEBPS/nav.xhtml                          (epub3 nav doc)
 *   OEBPS/toc.ncx                            (epub2 fallback TOC)
 *   OEBPS/styles.css
 *   OEBPS/cover.<ext>                        (optional)
 *   OEBPS/chapters/ch-NNNN.xhtml             (one per chapter)
 *
 * The chapter HTML is generated by `marked` and wrapped in a minimal
 * XHTML doctype that e-readers like Apple Books and Calibre parse.
 */

import { marked } from 'marked';
import { buildZip, ZipEntry } from './zip';

export interface EpubChapter {
  title: string;
  markdown: string;
}

export interface EpubInput {
  title: string;
  author: string;
  language?: string;
  identifier?: string;
  publisher?: string;
  chapters: EpubChapter[];
  cover?: { bytes: Buffer; mimeType: 'image/png' | 'image/jpeg' };
}

const STYLES_CSS = `
body { font-family: Georgia, "Times New Roman", serif; line-height: 1.5; padding: 1em 1.5em; }
h1, h2, h3 { font-family: -apple-system, "Helvetica Neue", sans-serif; line-height: 1.2; }
h1 { font-size: 1.8em; margin: 1.4em 0 0.4em; }
h2 { font-size: 1.4em; margin: 1.2em 0 0.4em; }
h3 { font-size: 1.15em; margin: 1em 0 0.3em; }
pre, code { font-family: "SFMono-Regular", Menlo, Consolas, monospace; }
pre { background: #f3f3f3; padding: 0.6em 0.8em; border-radius: 4px; overflow-x: auto; }
code { background: #f3f3f3; padding: 0.05em 0.3em; border-radius: 3px; }
blockquote { border-left: 3px solid #888; margin: 1em 0; padding: 0.2em 0.8em; color: #555; background: #fafafa; }
table { border-collapse: collapse; width: 100%; margin: 1em 0; }
th, td { border: 1px solid #ccc; padding: 6px 10px; text-align: left; }
th { background: #f0f0f0; }
img { max-width: 100%; }
`.trim();

export function buildEpub(input: EpubInput): Buffer {
  const language = input.language ?? 'en';
  const identifier = input.identifier ?? `urn:uuid:${pseudoUuid(input.title + input.author)}`;
  const now = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
  const publisher = input.publisher ?? 'Mark It Down';

  const entries: ZipEntry[] = [];

  entries.push({
    name: 'mimetype',
    data: Buffer.from('application/epub+zip', 'ascii'),
    method: 0,
  });

  entries.push({
    name: 'META-INF/container.xml',
    data: Buffer.from(
      `<?xml version="1.0" encoding="UTF-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>
`,
      'utf8',
    ),
  });

  const chapterFilenames = input.chapters.map((_, i) =>
    `chapters/ch-${String(i + 1).padStart(4, '0')}.xhtml`,
  );

  // Chapters
  input.chapters.forEach((chapter, i) => {
    const html = chapterHtml(chapter);
    entries.push({ name: `OEBPS/${chapterFilenames[i]}`, data: Buffer.from(html, 'utf8') });
  });

  entries.push({
    name: 'OEBPS/styles.css',
    data: Buffer.from(STYLES_CSS, 'utf8'),
  });

  // Cover
  let coverManifestId: string | undefined;
  let coverHref: string | undefined;
  if (input.cover) {
    coverHref = input.cover.mimeType === 'image/png' ? 'cover.png' : 'cover.jpg';
    coverManifestId = 'cover-image';
    entries.push({
      name: `OEBPS/${coverHref}`,
      data: input.cover.bytes,
    });
  }

  entries.push({
    name: 'OEBPS/nav.xhtml',
    data: Buffer.from(navXhtml(input, chapterFilenames), 'utf8'),
  });

  entries.push({
    name: 'OEBPS/toc.ncx',
    data: Buffer.from(tocNcx(input, identifier, chapterFilenames), 'utf8'),
  });

  entries.push({
    name: 'OEBPS/content.opf',
    data: Buffer.from(
      contentOpf({
        title: input.title,
        author: input.author,
        language,
        identifier,
        modified: now,
        publisher,
        chapterFilenames,
        coverHref,
        coverManifestId,
        coverMime: input.cover?.mimeType,
      }),
      'utf8',
    ),
  });

  return buildZip(entries);
}

function chapterHtml(chapter: EpubChapter): string {
  const body = marked.parse(chapter.markdown, { async: false }) as string;
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta charset="utf-8"/>
<title>${escapeXml(chapter.title)}</title>
<link rel="stylesheet" type="text/css" href="../styles.css"/>
</head>
<body>
<h1>${escapeXml(chapter.title)}</h1>
${cleanXhtml(body)}
</body>
</html>
`;
}

function navXhtml(input: EpubInput, chapterFilenames: string[]): string {
  const items = input.chapters
    .map((c, i) => `      <li><a href="${chapterFilenames[i]}">${escapeXml(c.title)}</a></li>`)
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
<meta charset="utf-8"/>
<title>${escapeXml(input.title)}</title>
</head>
<body>
<nav epub:type="toc" id="toc">
  <h1>${escapeXml(input.title)}</h1>
  <ol>
${items}
  </ol>
</nav>
</body>
</html>
`;
}

function tocNcx(input: EpubInput, identifier: string, chapterFilenames: string[]): string {
  const items = input.chapters
    .map(
      (c, i) => `  <navPoint id="navPoint-${i + 1}" playOrder="${i + 1}">
    <navLabel><text>${escapeXml(c.title)}</text></navLabel>
    <content src="${chapterFilenames[i]}"/>
  </navPoint>`,
    )
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
<head>
  <meta name="dtb:uid" content="${escapeXml(identifier)}"/>
  <meta name="dtb:depth" content="1"/>
  <meta name="dtb:totalPageCount" content="0"/>
  <meta name="dtb:maxPageNumber" content="0"/>
</head>
<docTitle><text>${escapeXml(input.title)}</text></docTitle>
<navMap>
${items}
</navMap>
</ncx>
`;
}

function contentOpf(args: {
  title: string;
  author: string;
  language: string;
  identifier: string;
  modified: string;
  publisher: string;
  chapterFilenames: string[];
  coverHref?: string;
  coverManifestId?: string;
  coverMime?: 'image/png' | 'image/jpeg';
}): string {
  const manifest = [
    `    <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>`,
    `    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>`,
    `    <item id="styles" href="styles.css" media-type="text/css"/>`,
    ...args.chapterFilenames.map(
      (f, i) => `    <item id="ch-${i + 1}" href="${f}" media-type="application/xhtml+xml"/>`,
    ),
  ];
  if (args.coverHref && args.coverManifestId && args.coverMime) {
    manifest.push(
      `    <item id="${args.coverManifestId}" href="${args.coverHref}" media-type="${args.coverMime}" properties="cover-image"/>`,
    );
  }
  const spine = args.chapterFilenames
    .map((_, i) => `    <itemref idref="ch-${i + 1}"/>`)
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="bookid">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="bookid">${escapeXml(args.identifier)}</dc:identifier>
    <dc:title>${escapeXml(args.title)}</dc:title>
    <dc:creator>${escapeXml(args.author)}</dc:creator>
    <dc:language>${escapeXml(args.language)}</dc:language>
    <dc:publisher>${escapeXml(args.publisher)}</dc:publisher>
    <meta property="dcterms:modified">${escapeXml(args.modified)}</meta>
  </metadata>
  <manifest>
${manifest.join('\n')}
  </manifest>
  <spine toc="ncx">
${spine}
  </spine>
</package>
`;
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Marked emits HTML5 (e.g. `<br>`, `<hr>`); EPUB 3 strict parsers expect
 * XHTML. Self-close the void elements to keep validators happy.
 */
function cleanXhtml(html: string): string {
  return html
    .replace(/<br\s*\/?>/g, '<br/>')
    .replace(/<hr\s*\/?>/g, '<hr/>')
    .replace(/<img([^>]*?)>/g, (_, attrs) => `<img${attrs}/>`);
}

function pseudoUuid(seed: string): string {
  // Deterministic 32-hex-char id derived from seed — not a cryptographic UUID,
  // just enough to satisfy EPUB's unique-identifier requirement per book.
  let h = 0;
  for (let i = 0; i < seed.length; i++) {
    h = ((h << 5) - h + seed.charCodeAt(i)) | 0;
  }
  const hex = (h >>> 0).toString(16).padStart(8, '0');
  return `${hex}-${hex.slice(0, 4)}-${hex.slice(4)}-${hex.slice(0, 4)}-${hex}${hex.slice(0, 4)}`;
}
