// Code generated by togo (seeder) — uses the factory; adjust the count freely.
package seeders

import (
	"context"

	"github.com/fadymondy/mark-it-down/apps/web/internal/app"
	"github.com/fadymondy/mark-it-down/apps/web/internal/factories"
)

// SeedNote inserts fake Notes via the factory.
func SeedNote(ctx context.Context, a *app.App) error {
	_, err := factories.Notes(a).Count(5).Create(ctx)
	return err
}
