// Code generated by togo. DO NOT EDIT.
package seeders

import (
	"context"

	"github.com/fadymondy/mark-it-down/apps/web/internal/app"
)

// SeedAll runs every resource seeder. Regenerated from togo.resources.yaml.
func SeedAll(ctx context.Context, a *app.App) error {
	if err := SeedNote(ctx, a); err != nil {
		return err
	}
	return nil
}
