// Code generated by togo. DO NOT EDIT.
//
// Installed plugins are blank-imported here so their init() registers them
// with the kernel for auto-discovery. Managed by `togo install`.
package plugins

import (
	_ "github.com/togo-framework/auth"
	_ "github.com/togo-framework/auth-dev"
	_ "github.com/togo-framework/auth-mfa"
	_ "github.com/togo-framework/mail"
)
