// Code generated by togo. REST (Huma) CRUD for notes via the ORM - safe to edit.
//
// Edited for the Mark It Down warehouse: every route except the public share
// endpoint requires an authenticated caller (session cookie or bearer PAT —
// resolved by the optionalIdentity kernel middleware), rows are scoped to the
// caller's user id (admins may pass ?all=1), and notes can be shared publicly
// through a random slug.
package rest

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"net/http"
	"strings"

	"github.com/microcosm-cc/bluemonday"
	"github.com/yuin/goldmark"

	"github.com/danielgtaylor/huma/v2"
	auth "github.com/togo-framework/auth"
	"github.com/togo-framework/validation"

	"github.com/fadymondy/mark-it-down/apps/web/internal/app"
	"github.com/fadymondy/mark-it-down/apps/web/internal/models"
	"github.com/fadymondy/mark-it-down/apps/web/internal/resources"
)

// caller returns the authenticated identity or a Huma 401.
func caller(ctx context.Context) (*auth.Identity, error) {
	id, ok := auth.IdentityFrom(ctx)
	if !ok || id == nil {
		return nil, huma.Error401Unauthorized("authentication required")
	}
	return id, nil
}

// ownedNote loads a note and enforces that the caller owns it (or is admin).
func ownedNote(ctx context.Context, a *app.App, id string) (*resources.NoteResponse, *auth.Identity, error) {
	who, err := caller(ctx)
	if err != nil {
		return nil, nil, err
	}
	row, err := models.Notes(a).Find(ctx, id)
	if err != nil {
		return nil, nil, huma.Error500InternalServerError("get failed", err)
	}
	if row == nil {
		return nil, nil, huma.Error404NotFound("note not found")
	}
	if row.UserID != who.ID && !who.HasRole("admin") {
		return nil, nil, huma.Error404NotFound("note not found")
	}
	resp := resources.TransformNote(*row)
	return &resp, who, nil
}

func newShareSlug() string {
	b := make([]byte, 8)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

// RegisterNoteRoutes mounts CRUD + share endpoints for notes.
func RegisterNoteRoutes(api huma.API, a *app.App) {
	huma.Register(api, huma.Operation{
		OperationID: "list-notes", Method: http.MethodGet, Path: "/api/notes",
		Summary: "List the caller's Notes", Tags: []string{"Note"},
	}, func(ctx context.Context, in *struct {
		Limit    int    `query:"limit" default:"100"`
		Offset   int    `query:"offset"`
		Category string `query:"category"`
		Tag      string `query:"tag"`
		Q        string `query:"q"`
		All      bool   `query:"all" doc:"admins only: list every user's notes"`
	}) (*struct {
		Body []resources.NoteResponse
	}, error) {
		who, err := caller(ctx)
		if err != nil {
			return nil, err
		}
		q := models.Notes(a).Order("updated_at DESC")
		if !(in.All && who.HasRole("admin")) {
			q = q.Where("user_id", "=", who.ID)
		}
		if in.Category != "" {
			q = q.Where("category", "=", in.Category)
		}
		rows, err := q.Limit(in.Limit).Offset(in.Offset).Get(ctx)
		if err != nil {
			return nil, huma.Error500InternalServerError("list failed", err)
		}
		// Tag + free-text filters run in Go: the ORM has no OR groups, and the
		// warehouse working set is per-user and small.
		if in.Tag != "" || in.Q != "" {
			needle := strings.ToLower(in.Q)
			filtered := rows[:0]
			for _, r := range rows {
				if in.Tag != "" {
					tags := ""
					if r.Tags != nil {
						tags = *r.Tags
					}
					if !hasTag(tags, in.Tag) {
						continue
					}
				}
				if needle != "" &&
					!strings.Contains(strings.ToLower(r.Title), needle) &&
					!strings.Contains(strings.ToLower(r.Body), needle) {
					continue
				}
				filtered = append(filtered, r)
			}
			rows = filtered
		}
		return &struct {
			Body []resources.NoteResponse
		}{Body: resources.TransformNotes(rows)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "get-note", Method: http.MethodGet, Path: "/api/notes/{id}",
		Summary: "Get a Note", Tags: []string{"Note"},
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct {
		Body resources.NoteResponse
	}, error) {
		resp, _, err := ownedNote(ctx, a, in.ID)
		if err != nil {
			return nil, err
		}
		return &struct {
			Body resources.NoteResponse
		}{Body: *resp}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "create-note", Method: http.MethodPost, Path: "/api/notes",
		DefaultStatus: http.StatusCreated, Summary: "Create a Note", Tags: []string{"Note"},
	}, func(ctx context.Context, in *struct {
		Body struct {
			Title    string  `json:"title" validate:"required"`
			Body     string  `json:"body"`
			Category *string `json:"category"`
			Tags     *string `json:"tags"`
		}
	}) (*struct {
		Body resources.NoteResponse
	}, error) {
		who, err := caller(ctx)
		if err != nil {
			return nil, err
		}
		if errs := validation.Validate(in.Body); errs.Any() {
			return nil, huma.Error422UnprocessableEntity(errs.Error())
		}
		row, err := models.Notes(a).Create(ctx, map[string]any{
			"title":     in.Body.Title,
			"body":      in.Body.Body,
			"category":  in.Body.Category,
			"tags":      in.Body.Tags,
			"user_id":   who.ID,
			"is_public": false,
		})
		if err != nil {
			return nil, huma.Error500InternalServerError("create failed", err)
		}
		a.Emit(ctx, "note.created", row)
		return &struct {
			Body resources.NoteResponse
		}{Body: resources.TransformNote(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "update-note", Method: http.MethodPut, Path: "/api/notes/{id}",
		Summary: "Update a Note", Tags: []string{"Note"},
	}, func(ctx context.Context, in *struct {
		ID   string `path:"id"`
		Body struct {
			Title    string  `json:"title"`
			Body     string  `json:"body"`
			Category *string `json:"category"`
			Tags     *string `json:"tags"`
		}
	}) (*struct {
		Body resources.NoteResponse
	}, error) {
		if _, _, err := ownedNote(ctx, a, in.ID); err != nil {
			return nil, err
		}
		if err := models.Notes(a).Where("id", "=", in.ID).Update(ctx, map[string]any{
			"title":    in.Body.Title,
			"body":     in.Body.Body,
			"category": in.Body.Category,
			"tags":     in.Body.Tags,
		}); err != nil {
			return nil, huma.Error500InternalServerError("update failed", err)
		}
		row, err := models.Notes(a).Find(ctx, in.ID)
		if err != nil || row == nil {
			return nil, huma.Error500InternalServerError("reload failed", err)
		}
		a.Emit(ctx, "note.updated", row)
		return &struct {
			Body resources.NoteResponse
		}{Body: resources.TransformNote(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "delete-note", Method: http.MethodDelete, Path: "/api/notes/{id}",
		DefaultStatus: http.StatusNoContent, Summary: "Delete a Note", Tags: []string{"Note"},
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct{}, error) {
		if _, _, err := ownedNote(ctx, a, in.ID); err != nil {
			return nil, err
		}
		if err := models.Notes(a).Where("id", "=", in.ID).Delete(ctx); err != nil {
			return nil, huma.Error500InternalServerError("delete failed", err)
		}
		a.Emit(ctx, "note.deleted", in.ID)
		return &struct{}{}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "share-note", Method: http.MethodPost, Path: "/api/notes/{id}/share",
		Summary: "Make a Note public and return its share slug", Tags: []string{"Note"},
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct {
		Body resources.NoteResponse
	}, error) {
		resp, _, err := ownedNote(ctx, a, in.ID)
		if err != nil {
			return nil, err
		}
		slug := newShareSlug()
		if resp.ShareSlug != nil && *resp.ShareSlug != "" {
			slug = *resp.ShareSlug // sharing is idempotent — keep existing links alive
		}
		if err := models.Notes(a).Where("id", "=", in.ID).Update(ctx, map[string]any{
			"is_public": true, "share_slug": slug,
		}); err != nil {
			return nil, huma.Error500InternalServerError("share failed", err)
		}
		row, err := models.Notes(a).Find(ctx, in.ID)
		if err != nil || row == nil {
			return nil, huma.Error500InternalServerError("reload failed", err)
		}
		return &struct {
			Body resources.NoteResponse
		}{Body: resources.TransformNote(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "unshare-note", Method: http.MethodDelete, Path: "/api/notes/{id}/share",
		Summary: "Make a Note private again", Tags: []string{"Note"},
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct {
		Body resources.NoteResponse
	}, error) {
		if _, _, err := ownedNote(ctx, a, in.ID); err != nil {
			return nil, err
		}
		if err := models.Notes(a).Where("id", "=", in.ID).Update(ctx, map[string]any{
			"is_public": false,
		}); err != nil {
			return nil, huma.Error500InternalServerError("unshare failed", err)
		}
		row, err := models.Notes(a).Find(ctx, in.ID)
		if err != nil || row == nil {
			return nil, huma.Error500InternalServerError("reload failed", err)
		}
		return &struct {
			Body resources.NoteResponse
		}{Body: resources.TransformNote(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "get-shared-note", Method: http.MethodGet, Path: "/api/shared/{slug}",
		Summary: "Read a publicly shared Note (no auth)", Tags: []string{"Note"},
	}, func(ctx context.Context, in *struct {
		Slug string `path:"slug"`
	}) (*struct {
		Body struct {
			Title     string `json:"title"`
			Body      string `json:"body"`
			HTML      string `json:"html"`
			UpdatedAt string `json:"updated_at"`
		}
	}, error) {
		row, err := models.Notes(a).
			Where("share_slug", "=", in.Slug).
			Where("is_public", "=", true).
			First(ctx)
		if err != nil {
			return nil, huma.Error500InternalServerError("lookup failed", err)
		}
		if row == nil {
			return nil, huma.Error404NotFound("shared note not found")
		}
		out := &struct {
			Body struct {
				Title     string `json:"title"`
				Body      string `json:"body"`
				HTML      string `json:"html"`
				UpdatedAt string `json:"updated_at"`
			}
		}{}
		out.Body.Title = row.Title
		out.Body.Body = row.Body
		out.Body.HTML = renderSafeHTML(row.Body)
		out.Body.UpdatedAt = row.UpdatedAt.Format("2006-01-02T15:04:05Z07:00")
		return out, nil
	})
}

// gfm renders Markdown and ugc sanitizes it (same pipeline as
// togo-framework/richtext, inlined because that plugin mounts routes at
// PriorityService which trips auth v0.8.0's late Router.Use).
var (
	gfm = goldmark.New()
	ugc = bluemonday.UGCPolicy()
)

func renderSafeHTML(md string) string {
	var buf bytes.Buffer
	if err := gfm.Convert([]byte(md), &buf); err != nil {
		return ""
	}
	return ugc.Sanitize(buf.String())
}

// hasTag reports whether the comma-separated tags column contains tag.
func hasTag(tags, tag string) bool {
	for _, t := range strings.Split(tags, ",") {
		if strings.EqualFold(strings.TrimSpace(t), tag) {
			return true
		}
	}
	return false
}
