// Code generated by togo. Factory — builds fake Notes via faker,
// persisted through the ORM. Used by seeders; customize the Definition freely.
package factories

import (
	"context"

	"github.com/togo-framework/faker"

	"github.com/fadymondy/mark-it-down/apps/web/internal/app"
	db "github.com/fadymondy/mark-it-down/apps/web/internal/db/gen"
	"github.com/fadymondy/mark-it-down/apps/web/internal/models"
)

// NoteFactory builds fake Note records.
type NoteFactory struct {
	app   *app.App
	count int
}

// Notes starts a factory for Notes.
func Notes(a *app.App) *NoteFactory {
	return &NoteFactory{app: a, count: 1}
}

// Count sets how many records Create() will make.
func (f *NoteFactory) Count(n int) *NoteFactory { f.count = n; return f }

// Definition returns fake attributes for one Note. Edit to taste.
func (f *NoteFactory) Definition() map[string]any {
	_ = faker.Word
	return map[string]any{
		"title":      faker.Name(),
		"body":       faker.Paragraph(),
		"category":   faker.Words(3),
		"tags":       faker.Words(3),
		"user_id":    faker.Words(3),
		"share_slug": faker.Words(3),
		"is_public":  faker.Bool(),
	}
}

// Create builds and persists Count records via the ORM.
func (f *NoteFactory) Create(ctx context.Context) ([]db.Note, error) {
	out := make([]db.Note, 0, f.count)
	for i := 0; i < f.count; i++ {
		row, err := models.Notes(f.app).Create(ctx, f.Definition())
		if err != nil {
			return out, err
		}
		out = append(out, *row)
	}
	return out, nil
}
