-- Code generated by togo. SQLite query fragment - safe to edit.
-- name: GetNote :one
SELECT * FROM notes WHERE id = ?;

-- name: ListNotes :many
SELECT * FROM notes ORDER BY created_at DESC LIMIT ? OFFSET ?;

-- name: CreateNote :one
INSERT INTO notes (title, body, category, tags, user_id, share_slug, is_public)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING *;

-- name: DeleteNote :exec
DELETE FROM notes WHERE id = ?;
